# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KycCli < Formula
  desc "Terminal-only crypto swap (the kyc.rip aggregator as a TUI)"
  homepage "https://swap.kyc.rip"
  version "0.1.40"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyc-rip/cli/releases/download/v0.1.40/kyc-cli_0.1.40_darwin_amd64.tar.gz"
      sha256 "195b7cdf4124ea00661285677981304ed8ca2b09db5ee74488d7a5aae2933764"

      define_method(:install) do
        bin.install "kyc-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyc-rip/cli/releases/download/v0.1.40/kyc-cli_0.1.40_darwin_arm64.tar.gz"
      sha256 "6439c665c3db63b44a7cdeee05dc321fa89019e4c1aa0c3f0f5271fb38514ddf"

      define_method(:install) do
        bin.install "kyc-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyc-rip/cli/releases/download/v0.1.40/kyc-cli_0.1.40_linux_amd64.tar.gz"
      sha256 "1799746b980b38eb7b192b09576a4ddf7b93bf8435e42981dbf4708c6bd81f4b"
      define_method(:install) do
        bin.install "kyc-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyc-rip/cli/releases/download/v0.1.40/kyc-cli_0.1.40_linux_arm64.tar.gz"
      sha256 "bc99eb740c66a814b6159741c681289d03481b7eff817980aa7409715c09162a"
      define_method(:install) do
        bin.install "kyc-cli"
      end
    end
  end

  test do
    system "#{bin}/kyc-cli", "--version"
  end
end
