# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KycCli < Formula
  desc "Terminal-only crypto swap (the kyc.rip aggregator as a TUI)"
  homepage "https://swap.kyc.rip"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyc-rip/sshwap/releases/download/v0.1.1/kyc-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "56e6a335ccf28155507f98fb2f14ee16fb8eaae8f5f53118f9531664e0e828c5"
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyc-rip/sshwap/releases/download/v0.1.1/kyc-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "a7fd53a8e637aa266a062220cd44570479fc4c8975ab44eab561a530aa0b87eb"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyc-rip/sshwap/releases/download/v0.1.1/kyc-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "d29a5a6f24cec10beadd4becd80fda3836d217293450bf501375ac84dd0a3d60"
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyc-rip/sshwap/releases/download/v0.1.1/kyc-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "cba5b5472982f2b73c38967e830c5c54970dc97ecb7217be0d3e952a0a06142e"
    end
  end

  def install
    bin.install "kyc-cli"
  end

  test do
    system "#{bin}/kyc-cli", "--version"
  end
end
